### ISSUE TITLE
Keep aspect ratio on viewer window

### ISSUE THREAD

**Issue by igorer88** [mtgto/Fomalhaut2#13]
The viewer window changes as the pages sizes. 
<img width="752" alt="imagen" src="https://github.com/user-attachments/assets/e2188334-befc-4e2d-b354-ee9b450480c9">

So sometimes the window gets out of scope when the image is bigger than the screen resolution. 
It's annoying to move the screen when the next image is bigger.
<img width="1259" alt="imagen" src="https://github.com/user-attachments/assets/f2f7e407-e374-4c2b-9022-28f9c470e926">

Is it possible to set a fixed size? So the image scale the aspect ratio to it.

Actually as the web version address this problem, but it would be nice to have it addressed on the native version too.
<img width="1440" alt="imagen" src="https://github.com/user-attachments/assets/424db6b3-b797-4675-af59-b3f3607929ef">

Thanks!

**Comment by mtgto** [comment]
> So sometimes the window gets out of scope when the image is bigger than the screen resolution.
It's annoying to move the screen when the next image is bigger.

~I thought I had implemented so that window would not be larger than the screen size, but it is probably a bug that it is not.~

~I will investigate. Thanks.~

I guess your comic has small first image and large images after that.
That's correct, isn't it?

I suppose it would be possible to provide an option to fix the window height for the first image. Is that what you want?

**Comment by igorer88** [comment]
yes, that's correct.

I think a better solution would be to set a fixed size for the window, and then scale the image based to that size. 

Another solution would be to set a max width and max height for the window. So it won' t re-scale if the image is bigger than the screen size.

**Comment by mtgto** [comment]
Done in [v1.7.0](https://github.com/mtgto/Fomalhaut2/releases/tag/1.7.0).
I submitted v1.7.0 to App Store Connect, so it will release in few days.
